name: Auto Release

on:
  push:
    branches:
      - main  # 或者使用 master，根据你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 这会自动由GitHub提供
      with:
        tag_name: v1.0.${{ github.run_number }}  # 使用版本号，例如 v1.0.1, v1.0.2 等
        release_name: Release v1.0.${{ github.run_number }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
